// src/components/creatorBody.vue
<script setup lang="ts">
import { ref } from "vue";
import { Month } from "./monthStructure";

const emit = defineEmits({
    update(month: Month) {},
});
const monthNameParts = ref(["", "", ""]);
const selectedDays = ref(0);

function SaveAndUpload() {
    monthNameParts.value.forEach((element) => {
        if (!element) {
            element = "";
        }
    });

    const days = selectedDays.value;
    const fullMonthName: string = `${monthNameParts.value[0] + monthNameParts.value[1] + monthNameParts.value[0]}`;
    const thunder: Month = { month: fullMonthName, days: days };

    console.log("Saving Event Executed");
    emit("update", thunder);
}
</script>

<template>
    <div class="">
        <span>
            <label class="pr-2 align-top">Month</label>
            <select
                size="6"
                v-model="monthNameParts[0]"
                class="mr-1 border w-15"
            >
                <option>j</option>
                <option>nov</option>
                <option>dec</option>
                <option>febr</option>
                <option>m</option>
                <option>sept</option>
            </select>
            <select
                size="6"
                v-model="monthNameParts[1]"
                class="mr-1 border w-15"
            >
                <option>octo</option>
                <option>em</option>
                <option>uly</option>
                <option>a</option>
                <option>une</option>
                <option>an</option>
            </select>
            <select
                size="6"
                v-model="monthNameParts[3]"
                class="mr-1 border w-15"
            >
                <option>ber</option>
                <option>y</option>
                <option>unary</option>
                <option>rch</option>
                <option>pril</option>
                <option>ugust</option>
            </select>
        </span>
    </div>
    <div class="pt-2">
        <span>
            <label class="p-1 pr-5">day</label>
            <input
                type="number"
                class="border p-1 w-10"
                :value="selectedDays"
            />
        </span>
    </div>
    <div class="card-actions justify-end m-2">
        <button class="btn btn-primary" @click="SaveAndUpload()">Save</button>
    </div>
</template>

// src/lib/components/CreatorBody.svelte
<script lang="ts">
  import type { Month } from "$lib/types/month";

  const firstParts = ["j", "nov", "dec", "febr", "m", "sept"];
  const secondParts = ["octo", "em", "uly", "a", "une", "an"];
  const thirdParts = ["ber", "y", "unary", "rch", "pril", "ugust"];

  let { onSave } = $props<{ onSave: (month: Month) => void }>();

  let monthNamePartOne = $state(firstParts[0]);
  let monthNamePartTwo = $state(secondParts[0]);
  let monthNamePartThree = $state(thirdParts[0]);
  let selectedDays = $state(30);

  const fullMonthName = $derived(`${monthNamePartOne}${monthNamePartTwo}${monthNamePartThree}`.trim());
  const canSave = $derived(fullMonthName.length > 0 && selectedDays > 0);

  function saveAndUpload() {
    if (!canSave) return;

    onSave({
      month: fullMonthName,
      days: selectedDays,
    });
  }
</script>

<div class="space-y-4">
  <div>
    <label class="label p-0 pb-2" for="month-name-part-one">
      <span class="label-text font-medium">Month</span>
    </label>

    <div class="grid grid-cols-3 gap-2">
      <select id="month-name-part-one" class="select select-bordered h-36" size="6" bind:value={monthNamePartOne}>
        {#each firstParts as monthPart}
          <option>{monthPart}</option>
        {/each}
      </select>
      <select class="select select-bordered h-36" size="6" bind:value={monthNamePartTwo}>
        {#each secondParts as monthPart}
          <option>{monthPart}</option>
        {/each}
      </select>
      <select class="select select-bordered h-36" size="6" bind:value={monthNamePartThree}>
        {#each thirdParts as monthPart}
          <option>{monthPart}</option>
        {/each}
      </select>
    </div>
  </div>

  <div>
    <label class="label p-0 pb-2" for="days-in-month">
      <span class="label-text font-medium">Days</span>
    </label>
    <input id="days-in-month" class="input input-bordered w-full max-w-24" type="number" min="1" bind:value={selectedDays} />
  </div>

  <div class="card-actions justify-end">
    <button class="btn btn-primary" onclick={saveAndUpload} disabled={!canSave}>Save</button>
  </div>
</div>
