// components_old/yearSlider.vue
<script setup>
const model = defineModel({ default: 0 });
</script>

<template>
    <span>
        <label class="pr-5">Year</label>
        <input
            v-model="model"
            type="text"
            class="border border-slate-500 p-1 w-30"
        />
        <input
            type="range"
            class="block p-2 w-full"
            min="-100000"
            max="100000"
            v-model="model"
        />
    </span>
</template>

// src/lib/components/YearSlider.svelte
<script lang="ts">
  let { year = $bindable(0) } = $props<{ year?: number }>();
</script>

<div class="space-y-3">
  <label class="label p-0" for="year-value">
    <span class="label-text font-medium">Year</span>
  </label>

  <input id="year-value" class="input input-bordered w-full" type="number" bind:value={year} />

  <input
    class="range range-primary"
    type="range"
    min="-100000"
    max="100000"
    step="1"
    bind:value={year}
  />
</div>
